In [1]:
import pandas as pd

df = pd.read_csv('OML_4G_DATA_OSS.csv')
df.head()

,Time,eNodeB Function Name,Cell Name,Frequency band,AVG_DL_USER_THROUGHPUT,L.Traffic.ActiveUser.DL.Avg,Date,Hour
0,2024-05-27 00:00:00,1288_KKO_KATI_4G,1288_KKO_KATI_1_L800,20,7543.2661,2.6076,2024-05-27,0
1,2024-05-27 00:00:00,1324_BKO_SOGONIKO_4G,1324_BKO_SOGONIKO_3_L800,20,9686.8516,0.8624,2024-05-27,0
2,2024-05-27 00:00:00,1560_BKO_SENOU-MEDINE_4G,1560_BKO_SENOU-MEDINE_2_L1800,3,12827.9154,1.8092,2024-05-27,0
3,2024-05-27 00:00:00,1605_BKO_NIARELA Mosque_4G,1605_BKO_NIARELA Mosque_1_L700,28,0.0000,0.0000,2024-05-27,0
4,2024-05-27 00:00:00,1634_BKO_DOUMANZANA_4G,1634_BKO_DOUMANZANA_3_L1800,3,18474.4263,0.7931,2024-05-27,0

# Data Cleaning

In [2]:
# Renaming Attributes
df.rename(columns={'AVG_DL_USER_THROUGHPUT':'Avg DL User Thrput kbps',
                   'L.Traffic.ActiveUser.DL.Avg':'Avg DL Traffic Active User'}, inplace=True)

df.head()

,Time,eNodeB Function Name,Cell Name,Frequency band,Avg DL User Thrput kbps,Avg DL Traffic Active User,Date,Hour
0,2024-05-27 00:00:00,1288_KKO_KATI_4G,1288_KKO_KATI_1_L800,20,7543.2661,2.6076,2024-05-27,0
1,2024-05-27 00:00:00,1324_BKO_SOGONIKO_4G,1324_BKO_SOGONIKO_3_L800,20,9686.8516,0.8624,2024-05-27,0
2,2024-05-27 00:00:00,1560_BKO_SENOU-MEDINE_4G,1560_BKO_SENOU-MEDINE_2_L1800,3,12827.9154,1.8092,2024-05-27,0
3,2024-05-27 00:00:00,1605_BKO_NIARELA Mosque_4G,1605_BKO_NIARELA Mosque_1_L700,28,0.0000,0.0000,2024-05-27,0
4,2024-05-27 00:00:00,1634_BKO_DOUMANZANA_4G,1634_BKO_DOUMANZANA_3_L1800,3,18474.4263,0.7931,2024-05-27,0

In [3]:
# Normalize Columns Names
df.columns = df.columns.str.strip().str.replace(r'[^\w]', '_', regex=True)

# Remove NIL
df.replace('NIL', pd.NA, inplace=True)

df.columns

Index(['Time', 'eNodeB_Function_Name', 'Cell_Name', 'Frequency_band',
       'Avg_DL_User_Thrput_kbps', 'Avg_DL_Traffic_Active_User', 'Date',
       'Hour'],
      dtype='object')

In [4]:
df.isnull().sum()

Time                          0
eNodeB_Function_Name          0
Cell_Name                     0
Frequency_band                0
Avg_DL_User_Thrput_kbps       0
Avg_DL_Traffic_Active_User    0
Date                          0
Hour                          0
dtype: int64

In [5]:
# Drop Duplicates
df.drop_duplicates()

,Time,eNodeB_Function_Name,Cell_Name,Frequency_band,Avg_DL_User_Thrput_kbps,Avg_DL_Traffic_Active_User,Date,Hour
0,2024-05-27 00:00:00,1288_KKO_KATI_4G,1288_KKO_KATI_1_L800,20,7543.2661,2.6076,2024-05-27,0
1,2024-05-27 00:00:00,1324_BKO_SOGONIKO_4G,1324_BKO_SOGONIKO_3_L800,20,9686.8516,0.8624,2024-05-27,0
2,2024-05-27 00:00:00,1560_BKO_SENOU-MEDINE_4G,1560_BKO_SENOU-MEDINE_2_L1800,3,12827.9154,1.8092,2024-05-27,0
3,2024-05-27 00:00:00,1605_BKO_NIARELA Mosque_4G,1605_BKO_NIARELA Mosque_1_L700,28,0.0000,0.0000,2024-05-27,0
4,2024-05-27 00:00:00,1634_BKO_DOUMANZANA_4G,1634_BKO_DOUMANZANA_3_L1800,3,18474.4263,0.7931,2024-05-27,0
...,...,...,...,...,...,...,...,...
5247854,2025-07-30 23:00:00,5402_KKO_THIONTALA_4G,5402_KKO_THIONTALA_2_L800,20,25149.1985,0.2585,2025-07-30,23
5247855,2025-07-30 23:00:00,4605_KYS_FARINCOUNDA_4G,4605_KYS_FARINCOUNDA_2_L800,20,7608.9002,1.4933,2025-07-30,23
5247856,2025-07-30 23:00:00,4597_KYS_SAME-OUOLOF_4G,4597_KYS_SAME-OUOLOF_1_L800,20,3292.5706,7.6997,2025-07-30,23
5247857,2025-07-30 23:00:00,4610_KYS_FADOUGOU_4G,4610_KYS_FADOUGOU_2_L1800,3,5537.6060,6.8472,2025-07-30,23
5247858,2025-07-30 23:00:00,5350_KKO_KATIBOUGOU-MEGUETAN_4G_NA,5350_KKO_KATIBOUGOU-MEGUETAN_3_L2600_NA,7,95241.6207,0.0675,2025-07-30,23

In [6]:
# Convert Object to String and Normalizing text fields
df['eNodeB_Function_Name'] = df['eNodeB_Function_Name'].astype('string')
df['eNodeB_Function_Name'] = df['eNodeB_Function_Name'].str.strip().str.replace(r'\s+', '', regex=True)
df['Cell_Name'] = df['Cell_Name'].astype('string')
df['Cell_Name'] = df['Cell_Name'].str.strip().str.replace(r'\s+', '', regex=True)

In [7]:
# Convert Object to Numeric
df['Avg_DL_User_Thrput_kbps'] = pd.to_numeric(df['Avg_DL_User_Thrput_kbps'])
df['Avg_DL_Traffic_Active_User'] = pd.to_numeric(df['Avg_DL_Traffic_Active_User'])

In [8]:
# Convert Object to Category
df['Frequency_band'] = df['Frequency_band'].astype('category')

In [9]:
# Converting Object to Date
df['Time'] = pd.to_datetime(df['Time'])
df['Date'] = pd.to_datetime(df['Date'])
df['Hour'] = pd.to_datetime(df['Hour'], format='%H').dt.strftime('%H:%M:%S')